name: bnkandroid
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ← 업데이트/추가 (PDF 뷰어/다운로드용)
  http: ^1.2.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  syncfusion_flutter_pdfviewer: ^26.1.40
  open_filex: ^4.5.0

  # 기존
  flutter_staggered_animations: ^1.0.0
  visibility_detector: ^0.4.0
  screen_protector: ^1.4.0
  screenshot_callback: ^3.0.1
  web_socket_channel: ^3.0.1
  stomp_dart_client: ^2.1.3
  geolocator: ^14.0.2

  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.2+7
  webview_flutter_android: ^4.10.0
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.3.1
  share_plus: ^10.0.2

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  flutter_naver_map: ^1.4.1+1
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.2.1
  image_gallery_saver_plus: ^4.0.1

  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/postcode.html
